"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const index_1 = require("./index");
const compliance_1 = require("./compliance");
exports.router = (0, express_1.Router)();
exports.router.use("/", index_1.accountsRouter);
exports.router.use("/compliance", compliance_1.accountRouter);
exports.default = exports.router;
