// functions/src/support/supportService.ts
// Serviço de suporte AI unificado para Momentum
// Usa o aiClient (OpenAI/Gemini) para gerar respostas de suporte
// e é consumido pelo módulo Express em modules/support.ts

import { aiClient } from "../utils/aiClient";

/**
 * Dados principais enviados pela rota de suporte.
 * É o que vem do frontend / API.
 */
export interface SupportRequestInput {
  tenantId: string;
  userId: string;
  question: string;
  locale?: string; // "pt-BR", "en", etc.
  planTier?: string; // starter | pro | business | enterprise | cfo
}

/**
 * Contexto adicional vindo da camada HTTP (req/tenant).
 * É montado em modules/support.ts e passado junto para enriquecer o prompt.
 */
export interface SupportRequestContext {
  tenantId: string;
  userId: string;
  locale: string;
  plan?: string | null;
  traceId?: string;
}

/**
 * Resposta final devolvida pela camada de serviço para a rota de suporte.
 */
export interface SupportResponse {
  answer: string;
  language: string;
  topics?: string[];
  confidence?: number;
}

/**
 * Constrói o prompt de suporte a partir da pergunta, plano e contexto.
 * Aqui é o lugar certo para ajustar o “tom” e as instruções de negócio.
 */
function buildSupportPrompt(
  input: SupportRequestInput,
  ctx: SupportRequestContext
): string {
  const locale = input.locale || ctx.locale || "pt-BR";
  const question = (input.question ?? "").trim();
  const plan = input.planTier || ctx.plan || "starter";

  const baseIntro =
    locale.startsWith("pt")
      ? `Você é o assistente de SUPORTE OFICIAL da plataforma Momentum, um SaaS financeiro para empresas.

Seu papel é exclusivamente de SUPORTE AO PRODUTO, ajudando o usuário a:
- entender como usar o Momentum,
- navegar pelo painel e recursos,
- interpretar relatórios gerados pelo sistema,
- entender limites de plano e créditos de IA.

Você NÃO é o CFO do cliente, nem um consultor contábil, tributário, jurídico ou médico.`
      : `You are the OFFICIAL SUPPORT ASSISTANT of Momentum, a financial SaaS for businesses.

Your role is strictly PRODUCT SUPPORT. You help the user to:
- understand how to use Momentum,
- navigate the dashboard and features,
- interpret reports generated by the system,
- understand plan limits and AI credits.

You are NOT the client’s CFO, nor a tax, accounting, legal or medical advisor.`;

  const capabilitiesBlock =
    locale.startsWith("pt")
      ? `O que você PODE responder:
- Dúvidas sobre uso do sistema Momentum (como usar módulos, filtros, dashboards, CFO, Pulse, Voz, Mercado).
- Explicar quais recursos existem em cada plano, limites de créditos de IA/voz e como fazer upgrade.
- Ajudar o usuário a entender um relatório ou indicador gerado pelo Momentum (ex.: fluxo de caixa, margem, runway, etc.).
- Dar exemplos genéricos de boas práticas financeiras, SEM personalizar com dados que você não tem.

O que você NÃO PODE responder:
- Consultoria ou recomendações específicas de CONTABILIDADE, TRIBUTOS, FISCAL, trabalhista ou jurídica.
- Decisões externas do negócio do cliente (ex.: “devo demitir X pessoas?” ou “qual alíquota exata devo usar?”).
- Diagnósticos médicos ou qualquer orientação de saúde.
- Opiniões políticas, religiosas ou que fujam do escopo de finanças e uso do sistema.

Se a pergunta for fora de escopo, explique com clareza que não pode responder e redirecione o usuário para o contador, jurídico ou médico, quando apropriado.`
      : `What you CAN answer:
- Questions about how to use Momentum (modules, filters, dashboards, CFO, Pulse, Voice, Market, etc.).
- Explain which features exist in each plan, AI/voice credit limits, and how to upgrade.
- Help the user understand a report or KPI generated by Momentum (e.g. cash flow, margin, runway, etc.).
- Provide generic examples of financial best practices WITHOUT inventing or guessing specific data.

What you MUST NOT answer:
- Specific tax, accounting, payroll, or legal advice.
- External business decisions (e.g. “should I fire people?” or “which exact tax rate must I use?”).
- Medical/health advice or any diagnosis.
- Political or religious opinions, or anything outside finance/product scope.

If the question is out of scope, clearly say you cannot answer and redirect the user to their accountant, legal advisor or doctor when appropriate.`;

  const planBlock =
    locale.startsWith("pt")
      ? `Plano do usuário: ${plan}.
Se a dúvida envolver recursos que não existem no plano atual, explique isso com delicadeza e, se fizer sentido, sugira o upgrade de forma objetiva e transparente (sem pressão exagerada).`
      : `User plan: ${plan}.
If the question involves features not available in the current plan, explain that gently and, if appropriate, suggest an upgrade in a clear and transparent way (no aggressive sales pressure).`;

  const guidelines =
    locale.startsWith("pt")
      ? `Regras gerais de resposta:
- Priorize respostas práticas, com passos claros (por exemplo: “Clique em CFO → depois em Simulações → escolha o cenário…”).
- Organize respostas em listas e passos numerados quando fizer sentido.
- Se for uma dúvida sobre uso do sistema, explique “onde clicar” e “qual caminho seguir”.
- Se não tiver certeza sobre algo, seja honesto e diga o que você sabe e o que não sabe.
- Não invente dados financeiros específicos do cliente (valores, saldos, impostos exatos, etc.).
- Mantenha sempre um tom amigável, profissional e encorajador, sem jargão técnico excessivo.`
      : `General answer rules:
- Prioritize practical answers with clear step-by-step instructions (e.g. “Click on CFO → then Simulations → choose the scenario…”).
- Use bullet points and numbered steps when helpful.
- If the question is about using the system, explain “where to click” and “which path to follow”.
- If you are not sure about something, be honest and explain what you do and don’t know.
- Do not invent specific financial data (amounts, balances, exact taxes, etc.).
- Keep a friendly, professional and encouraging tone, avoiding unnecessary jargon.`;

  const questionBlock =
    locale.startsWith("pt")
      ? `Pergunta do usuário (escopo: suporte ao produto Momentum):\n${question}`
      : `User question (scope: Momentum product support):\n${question}`;

  return [
    baseIntro,
    "",
    capabilitiesBlock,
    "",
    planBlock,
    "",
    guidelines,
    "",
    questionBlock,
  ].join("\n");
}

/**
 * Função principal usada pelas rotas de suporte para obter
 * uma resposta gerada por IA.
 *
 * Ela não conhece Express nem Firestore — só recebe os dados
 * estruturados e devolve uma resposta de alto nível.
 */
export async function getSupportAnswer(
  input: SupportRequestInput,
  ctx: SupportRequestContext
): Promise<SupportResponse> {
  const locale = input.locale || ctx.locale || "pt-BR";

  const prompt = buildSupportPrompt(input, ctx);

  let text = "";
  try {
    const result = await aiClient(prompt, {
      tenantId: input.tenantId,
      userId: input.userId,
      model: "openai", // ou "gemini" — o aiClient decide pelo provider/ambiente
      promptKind: "support.auto", // identifica que é suporte (escopo de sessão)
      locale,
    });

    text = (result && (result as any).text) || "";
  } catch (err: any) {
    // Em caso de falha na IA, log é feito dentro do próprio aiClient.
    // Aqui apenas garantimos que não vamos quebrar a API de suporte.
    text = "";
  }

  const language = locale;

  const answer =
    text && text.trim().length > 0
      ? text
      : language.startsWith("pt")
      ? "Desculpe, não consegui gerar uma resposta de suporte agora. Tente novamente em alguns instantes."
      : "Sorry, I couldn't generate a support answer right now. Please try again in a moment.";

  const response: SupportResponse = {
    answer,
    language,
    topics: [], // pode ser enriquecido depois (ex.: classificação de tópicos via IA)
    confidence: 0.8, // valor fixo por enquanto; dá para evoluir depois
  };

  return response;
}
